default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: homeshare_development

test:
  <<: *default
  database: homeshare_test

production:
  <<: *default
  database: homeshare_production
  username: homeshare
  password: <%= ENV['HOMESHARE_DATABASE_PASSWORD'] %>
