# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdbf5914cc66d84487518dd1e953c13044cb1907dd388a26e45a14832d9f2f5168ea0f07e456b1e595a9accb11eba4a295d8e9754446eff0897751db3b9a1aed

test:
  secret_key_base: a7b3c1ef4335c846f7b42936527d86fdae9fa5ac62e96465905d3257d502047538ef9684aad4355fb80c1ea4e8c4cf1f35beeae80942ac923f23dee71fab8c08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
